inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'


# scope -> (params) 引数を囲む記述を認める
Layout/SpaceInLambdaLiteral:
  Enabled: false

# sessions_controller.rbのafter_sign_out_path_forメソッド
Lint/UnusedMethodArgument:
  Enabled: false

# 要確認のため退避 models/community.rbの users = User.where(id: user_ids)
Lint/UselessAssignment:
  Enabled: false
