inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'


# scope -> (params) 引数を囲む記述を認める
Layout/SpaceInLambdaLiteral:
  Enabled: false
